ALTER SESSION SET CURRENT_SCHEMA = POBYRNE;
/*SELECT * FROM BUILDER2.STOCK;
DESCRIBE BUILDER2.STOCK;
DESCRIBE PARTS;
SELECT * FROM STOCK;
SELECT STOCK_CODE, STOCK_DESCRIPTION, UNIT_PRICE, UNITCOSTPRICE , (UNIT_PRICE - UNITCOSTPRICE) FROM BUILDER2.STOCK;
SELECT STOCK_CODE, STOCK_DESCRIPTION, TO_CHAR(UNIT_PRICE, 'U9,999.99'), TO_CHAR(UNITCOSTPRICE, 'U9,999.99'), TO_CHAR(UNIT_PRICE - UNITCOSTPRICE, 'U9,999.99') FROM BUILDER2.STOCK;
SELECT STOCK_CODE "Stock Code", STOCK_DESCRIPTION "Stock Description", TO_CHAR(UNIT_PRICE, 'U9,999.99') "Price", TO_CHAR(UNITCOSTPRICE, 'U9,999.99') "Cost", TO_CHAR(UNIT_PRICE - UNITCOSTPRICE, 'U9,999.99') "Profit" FROM BUILDER2.STOCK;
SELECT sysdate FROM STOCK;
SELECT STOCK_CODE, STOCK_DESCRIPTION, STOCK_LEVEL, REORDER_LEVEL FROM STOCK;
SELECT STOCK_CODE, UNIT_PRICE * 10/100;
*/


/*Lab 1 Assessment*/
/*
DESCRIBE MOVIES;
SELECT * FROM POBYRNE.MOVIES;
SELECT MTITLE FROM POBYRNE.MOVIES WHERE (GENRE = 'documentary');
*/
