/*DESCRIBE POBYRNE.HOTEL;

DROP TABLE MY_HOTEL;
CREATE TABLE MY_HOTEL AS (SELECT HOTEL_NO,NAME,ADDRESS FROM POBYRNE.HOTEL);

ALTER TABLE MY_HOTEL ADD NIGHTLY_FEE NUMBER(6,2);

UPDATE MY_HOTEL
SET NIGHTLY_FEE = 150 WHERE HOTEL_NO > 400;

ALTER TABLE MY_HOTEL ADD CONSTRAINT HOTELNO PRIMARY KEY(HOTEL_NO);

CREATE TABLE MY_BOOKING
(
  BOOKCODE NUMBER(8) PRIMARY KEY,
  START_DATE DATE not null,
  END_DATE DATE not null,
  HOTEL_NO NUMBER(6) not null REFERENCES MY_HOTEL
);

INSERT INTO MY_BOOKING VALUES(12345678, '12-FEB-16', '12-MAR-16', 403);
INSERT INTO MY_BOOKING VALUES(52149658, '12-FEB-16', '12-MAR-16', 404);
INSERT INTO MY_BOOKING VALUES(74853152, '12-FEB-16', '12-MAR-16', 302);
INSERT INTO MY_BOOKING VALUES(48313584, '12-FEB-16', '12-MAR-16', 300);

SELECT * FROM MY_BOOKING;
*/

/*
DESCRIBE POBYRNE.PAINTER;
DROP TABLE ARTIST;
CREATE TABLE ARTIST AS (SELECT PAINTER_ID, PAINTER_NAME,
                        PAINTER_GENRE FROM POBYRNE.PAINTER);
ALTER TABLE ARTIST ADD DOD DATE;
UPDATE ARTIST
SET DOD = null; 
ALTER TABLE ARTIST ADD CONSTRAINT PAINTERID PRIMARY KEY(PAINTER_ID);

DROP TABLE PAINTING;
CREATE TABLE PAINTING
(
  CAT_NO NUMBER(6) not null,
  TITLE VARCHAR2(50) not null,
  YEAR_PAINTED NUMBER(4) not null,
  PAINTER_ID CHAR(6) not null REFERENCES ARTIST
);

INSERT INTO PAINTING VALUES(123456, 'SUNSET', 1234, 'IMP001');
INSERT INTO PAINTING VALUES(561552, 'DAWN', 4321, 'PIM002');
INSERT INTO PAINTING VALUES(154652, 'DUSK', 5212, 'CUB001');
INSERT INTO PAINTING VALUES(456821, 'FALL', 3215, 'POP001');

UPDATE ARTIST
SET DOD = '30-APR-1883' WHERE PAINTER_NAME = 'Edouard Manet';

UPDATE ARTIST
SET DOD = '29-JUL-1890' WHERE PAINTER_NAME = 'Vincent Van Gogh';

UPDATE ARTIST
SET DOD = '08-APR-1973' WHERE PAINTER_NAME = 'Pablo Picasso';

UPDATE ARTIST
SET DOD = '22-FEB-1987' WHERE PAINTER_NAME = 'Andy Warhol';

--SELECT * FROM ARTIST;
SELECT * FROM PAINTING;
*/


/*Week 4 eval */
DESCRIBE POBYRNE.EMPLOYEE;

CREATE TABLE EMP AS (SELECT ENAME, ENO, EDOB FROM POBYRNE.EMPLOYEE);

ALTER TABLE EMP ADD CURRENT_PROJECT VARCHAR(60);
ALTER TABLE EMP ADD CONSTRAINT CURPROJECT CHECK(CURRENT_PROJECT IS NOT NULL);
ALTER TABLE EMP ADD CONSTRAINT E_NO PRIMARY KEY(ENO);

--INSERT INTO EMP VALUES();
/*CREATE TABLE HOLIDAY
(
  ENO 
);
*/







